### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by cedricziel** [Superbalist/flysystem-google-storage#12]
Could you please bump the version number, so we can get the latest changes without requiring `dev-master`?

Thank you :)

**Comment by csspcc** [comment]
It would be great if you could bump the version, I really need this for my project. Thanks.

**Comment by matthewgoslett** [comment]
Hey
Sorry for delay, will get this live today.
Thanks

**Comment by csspcc** [comment]
Hey, is there any news about this?

**Comment by cedricziel** [comment]
Ping :)

**Comment by matthewgoslett** [comment]
Resolved in https://github.com/Superbalist/flysystem-google-storage/releases/tag/1.0.1

**Comment by matthewgoslett** [comment]
and apologies for the delay with this! :)
