### ISSUE TITLE
Error moving file from GCS Bucket to local file system

### ISSUE THREAD

**Issue by paulcanning** [Superbalist/flysystem-google-storage#14]
I am unable to move files from a GCS Bucket to a local file volume, but I can move it from the local file volume to a GCS Bucket.

No apparent PHP errors, just elFinder fails and shows a friendly error popup.

**Comment by matthewgoslett** [comment]
It sounds like this is an issue with elFinder?  I haven't looked too thoroughly but they don't appear to depend on our package.

**Comment by paulcanning** [comment]
It's a bit of both to be honest. Yes, its an elFinder issue as the paste function is failing, but that's because its trying to paste form GCS to a local filesystem, something elFinder doesn't do out of the box, as they didn't write the GCS adapter.

**Comment by matthewgoslett** [comment]
I don't quite see how we're connected to elFinder.  Have you written a custom adapter for them to integrate with GCS?  I can't find any reference to our package in their codebase.

**Comment by paulcanning** [comment]
Your package is for Flysystem, and Flysystem works with elFinder. elFinder does not work with GCS "out-of-the-box", which is where you package comes in to play.
