### ISSUE TITLE
elFinder really slow to retrieve GCS bucket that has a lot of sub folders

### ISSUE THREAD

**Issue by paulcanning** [Superbalist/flysystem-google-storage#17]
I am using the GCS FlySystem with some success, but when I have a GCS bucket set as a root volume, that has a lot of sub-folders, it is taking forever to load.

Is there anything I can do to speed this up at all?

**Comment by matthewgoslett** [comment]
I'd recommend using the CachedAdapter from Flysystem on top of our adapter.  We don't control the latency or speed between the adapter and Google Storage.  We use the https://github.com/google/google-api-php-client package underneath the hood.

We haven't had any slowness issues from production to Google Storage but it is sluggish from our office, so it's completely dependent on where you're accessing the bucket from.

**Comment by matthewgoslett** [comment]
I just saw the issue title now.  It sounds like this is an elFinder related issue and they don't depend on our package.
Thanks

**Comment by paulcanning** [comment]
Sadly I am unable to get any form of Cache adapter working alongside GCS :(

**Comment by matthewgoslett** [comment]
Here is some sample code:
```
$credentials = new \Google_Auth_AssertionCredentials(
    '[your service account]',
    [\Google_Service_Storage::DEVSTORAGE_FULL_CONTROL],
    file_get_contents('[[path to the p12 key file]]'),
    '[[your secret]]'
);

$client = new \Google_Client();
$client->setAssertionCredentials($credentials);
$client->setDeveloperKey('[[your developer key]]');

$service = new \Google_Service_Storage($client);

$adapter = new GoogleStorageAdapter($service, '[[your bucket name]]')

$store = new \League\Flysystem\Cached\Storage\Memory();
$cachedAdapter = new \League\Flysystem\Cached\CachedAdapter($adapter, $store);

$filesystem = new Filesystem($cachedAdapter);
```

**Comment by paulcanning** [comment]
I'm getting the error

> error: "Error calling GET https://www.googleapis.com/storage/v1/b/adgen-dev-rss/o/company?key=63ab887625ec1adb89974b0721ec422ac13ae0b5: (404) Not Found"
sync:true

**Comment by devDev1922** [comment]
@paulcanning I am having an issue somehow similar to your one. You was facing issue to load the google cloud folders. But I am having the issue in `rename`, `copy`, `move` operations. I posted my query [here](https://github.com/Studio-42/elFinder/issues/3301). Did you find any solution for your issue?? 

Many Thanks!

**Comment by paulcanning** [comment]
@devDev1922 christ, this was 5 years ago. I honestly cannot remember how I fixed it, if I ever did. The project was in a usable state, using GCS as the storage medium, so I suspect I either got it working, or found a work around. I know that doesn't help much.

**Comment by devDev1922** [comment]
@paulcanning Thank you for your quick response. I will look for solution of this.
