### ISSUE TITLE
GCS adapter suddenly stopped working

### ISSUE THREAD

**Issue by paulcanning** [Superbalist/flysystem-google-storage#20]
Last night my GCS root volume worked fine, this morning, it has started acting "odd".

The root volume now thinks it is locked, but I have no access controls on it at all.

I put a break point on the code where I initialise the adapter, and it looks like it has stopped authorizing it for some reason?

Code:

```
function googleCloud($bucket)
	{
		$credentials = new \Google_Auth_AssertionCredentials(
			'gcstest@my-project.iam.gserviceaccount.com',
			[\Google_Service_Storage::DEVSTORAGE_FULL_CONTROL],
			file_get_contents(set_realpath('my-project.p12')),
			'notasecret'
		);

		$client = new \Google_Client();
		$client->setAssertionCredentials($credentials);
		$client->setDeveloperKey('MY_KEY');

		$service = new \Google_Service_Storage($client);

		$adapter = new GoogleStorageAdapter($service, $bucket);

		return $adapter;
	}
```

**Comment by paulcanning** [comment]
OK, so I checked in a different browser, and it is OK. There seems to be an issue with caching permissions with GCS.

**Comment by matthewgoslett** [comment]
I'm not completely understanding.  We don't cache any credentials to Google Storage.  They get injected directly into the Google_Client instance.

**Comment by paulcanning** [comment]
I meant caching in the browser. Turns out this was an elFinder issue where they are using certian values for the caching that don't need setting for GCS roots and there for messed up.
