### ISSUE TITLE
Error creating new directories

### ISSUE THREAD

**Issue by paulcanning** [Superbalist/flysystem-google-storage#24]
Using elFinder to create a new directory in the root of a bucket, an error is thrown.

Whilst elFinder shows an error, the directory is actually created in the GCS (checked using the GCS console).

I think the problem is with this adapter though.

In the `upload()` method, `uploadType` is always set as `media` which may cause a conflict with elFinder.

It also seems to always want to set `data` to `$contents`, which is passed an empty string via `createDir()` which again is likely to cause issues?

**Comment by matthewgoslett** [comment]
GCS has no real concept of folder vs files, everything is really just an object.
To create what looks like a folder, it's just an empty object with a trailing /.
I'm not sure why elFinder would be choking, but my sample code seems to test fine:

```php
$newDir = $filesystem->createDir('new_directory_test');
var_dump($newDir);
var_dump($filesystem->listContents('new_directory_test'));

$objects = $filesystem->listContents();
foreach ($objects as $object) {
    if ($object['path'] == 'new_directory_test') {
        var_dump($object);
    }
}

bool(true)
array(0) {
}
array(8) {
  ["type"]=>
  string(3) "dir"
  ["dirname"]=>
  string(0) ""
  ["path"]=>
  string(18) "new_directory_test"
  ["timestamp"]=>
  int(1463657952)
  ["mimetype"]=>
  string(10) "text/plain"
  ["size"]=>
  string(1) "0"
  ["basename"]=>
  string(18) "new_directory_test"
  ["filename"]=>
  string(18) "new_directory_test"
}
```

The only thing which may be odd to elFinder is the mimetype.  The upload() function calls Util::guessMimeType which returns 'text/plain' for empty string; so directories are created with mimetype 'text/plain'.  If I create a folder via the GCS console, folders are created with mimetype 'application/x-www-form-urlencoded;charset=UTF-8'.  I'm not 100% sure this would be the issue though.

Could this also be related to https://github.com/Superbalist/flysystem-google-storage/issues/23

**Comment by paulcanning** [comment]
I think it could have been connected the the bucket ACL, but I can't remember

**Comment by matthewgoslett** [comment]
Can you please test if this is still happening, so that we can mark this as resolved?

**Comment by paulcanning** [comment]
Sorry, I'll try and check this week for you.
