### ISSUE TITLE
Uncaught Error: Class 'Google_Auth_AssertionCredentials' not found

### ISSUE THREAD

**Issue by matthewgoslett** [Superbalist/flysystem-google-storage#26]
After composer updating, I now get the error:
PHP Fatal error:  Uncaught Error: Class 'Google_Auth_AssertionCredentials' not found

This was introduced in https://github.com/Superbalist/flysystem-google-storage/issues/5 when we allowed for both ~1.1|^2.0.0@RC of the google/apiclient to be installed.  At some point during RC and 2.0.0 final, the Google_Auth_AssertionCredentials class was removed.
See https://github.com/google/google-api-php-client/issues/748 and https://github.com/google/google-api-php-client/blob/master/UPGRADING.md#google_auth_assertioncredentials-has-been-removed
When we pushed this release allowing 2.0.0@RC, we incorrectly bumped the minor version and kept major as is.

**Comment by matthewgoslett** [comment]
cc @cedricziel 

I'm not quite sure of the smoothest way forward here.

I'm suggesting we:
1. Revert https://github.com/Superbalist/flysystem-google-storage/pull/6/files
2. Create a new release fixing existing implementations.
3. Create a new RC release allowing only RC2 to 2.0.0 and changing our code to support to the new credentials handling as per https://github.com/google/google-api-php-client/blob/master/UPGRADING.md#google_auth_assertioncredentials-has-been-removed

**Comment by cedricziel** [comment]
I'd say:

1.) Branch off 1.x, Remove the 2.0 constraint (or to cause less harm pin the last working RC) and release a new patch version as a fix for existing users
2.) on master, use a constraint on the final 2.0 client and tag a new major version

I'm pretty sure that's the way to go :)

**Comment by cedricziel** [comment]
So basically what you're saying, @matthewgoslett  :D

**Comment by matthewgoslett** [comment]
I can't seem to find any RC version which still has the Google_Auth_AssertionCredentials class and old way of defining service credentials.
Can you confirm how you have it working your side, form when you requested the 2.0.0@RC be allowed?

**Comment by matthewgoslett** [comment]
Fixed in release 1.0.4 - https://github.com/Superbalist/flysystem-google-storage/releases/tag/1.0.4

I'm going to work on a new RC2 our side which uses the updated google/apiclient.
Apologies for the breakage here.

**Comment by matthewgoslett** [comment]
I've allowed for google/apiclient 2.0.0@RC in https://github.com/Superbalist/flysystem-google-storage/releases/tag/2.0.0-RC1

**Comment by cedricziel** [comment]
Thx Matthew - it's currently a bit out of scope, but I'll get back to testing and improving.
