### ISSUE TITLE
Stream uploads?

### ISSUE THREAD

**Issue by paulcanning** [Superbalist/flysystem-google-storage#34]
Doing tests with huge file uploads (10gb+) it seems that this adapter does not stream the upload, rather it just writes the file, presumably to memory, then finally to the bucket.

Is there any chance of getting the read and write stream functionality added in?

**Comment by paulcanning** [comment]
Hello?

**Comment by matthewgoslett** [comment]
We'll need to do some research into doing streamed uploads.  It depends on whether the google-api-php-client can do streamed or chunked uploads/downloads - https://github.com/google/google-api-php-client.

This seems possible on AppEngine (https://cloud.google.com/appengine/docs/php/googlestorage/).  They have a stream wrapper on AppEngine and also have access to the gs:// file handle.

**Comment by matthewgoslett** [comment]
This should now be possible with the updated v3.0.0 release.

We've switched to the google/cloud package package under the hood which uses resumable (streamed) uploads for files > 5MB.

**Comment by paulcanning** [comment]
I have moved to 3.0.2 but I have the issue of `Google_Auth_AssertionCredentials` being missing :/

**Comment by paulcanning** [comment]
In the latest v5.0.0, are files streamed straight to GCS?

When used with elFinder and the FlySystem adapter, it apparently seems that the file is uploaded to the server, then to GCS? (At least according to the author of elFinder)

https://github.com/Studio-42/elFinder/issues/1961#issuecomment-293231021
